# Site settings
title: Automation and Robotics Club
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Automation & Robotics Club 
user_description: Minim nostrud anim nulla esse esse laborum. Magna mollit id elit Lorem officia elit enim labore laborum. Ea cillum adipisicing dolore sint proident voluptate. Nisi culpa sint exercitation excepteur amet esse dolor ullamco aute cillum.Minim nostrud anim nulla esse esse laborum. Magna mollit id elit Lorem officia elit enim labore laborum. Ea cillum adipisicing dolore sint proident voluptate. Nisi culpa sint exercitation excepteur amet esse dolor ullamco aute cillum.
user_title: Electronics | Design | Programming
email: arc@hyderabad.bits-pilani.ac.in
twitter_username: lorem_ipsum
github_username:  arc-bphc
gplus_username:  lorem_ipsum
arc_logo : "assets/img/arclogo_bw_2021.png"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
